version : '3'
services:
  api:
    container_name: customer-service-quarkus
    build: .
    image: customer-service-quarkus0
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DB=mysql_db
    ports:
      - "8080:8080"
    links:
      - "mysql_db:mysql_db"
    depends_on:
      - mysql_db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
        reservations:
          memory: 128M
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/"
